const fs=require('node:fs');const path=require('node:path');const http=require('node:http');const assert=require('node:assert/strict');
const repo=path.resolve(__dirname,'..').replaceAll(String.fromCharCode(92),'/');
const {build}=require(repo+'/node_modules/esbuild');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const out=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'aristo-payroll-ui-'));
const mock=`
import {calculate,periods,basisAt} from '${repo}/functions/src/payrollDomain.ts';
export const db={},functions={};
const base={id:'e1',clientId:'1',name:'復職測試員工',email:'test@example.com',empNo:'1',employmentType:'part_time',startDate:'2026-10-01',endDate:'',defaultBaseSalary:220,defaultFoodAllowance:0,employmentHistory:[{id:'p1',type:'full_time',startDate:'2026-10-01',endDate:'2026-10-10'},{id:'p2',type:'part_time',startDate:'2026-10-20',endDate:null}],compensationHistory:[{id:'c1',effectiveDate:'2026-10-01',baseSalary:36000,foodAllowance:3000,insuranceBracket:36000,hasLaborIns:true,hasHealthIns:true},{id:'c2',effectiveDate:'2026-10-20',baseSalary:220,foodAllowance:0,insuranceBracket:28000,hasLaborIns:true,hasHealthIns:false}]};
const zero=Object.fromEntries(['baseSalary','fullAttendance','positionAllowance','performanceBonus','taxableOt','leaveDeduction','dailyShortage','lateDeduction','pensionSelf','foodAllowance','taxFreeOt','laborIns','healthIns','incomeTax','advancePay'].map(k=>[k,0]));
const data={employees:[base,{...base,id:'e2',name:'舊資料測試員工'}],monthlySalaries:[{...zero,id:'old1',clientId:'1',employeeId:'e2',month:'2026-10',baseSalary:32000},{...zero,id:'old2',clientId:'1',employeeId:'e2',month:'2026-10',baseSalary:32000}],payrollSlips:[]};const listeners=[];const receipts=new Map();window.__fixture={data,calls:[],failAfterSave:false};
export const collection=(_db,name,...parts)=>({name,parts});export const where=(...a)=>a;export const query=(c,...a)=>c;
const snapshot=name=>({docs:data[name].map(row=>({id:row.id,data:()=>row}))});
export const onSnapshot=(q,cb,fail)=>{if(location.search.includes('loadFailure')&&q.name==='monthlySalaries'){queueMicrotask(()=>fail(Error('模擬讀取失敗')));return()=>{};}listeners.push([q.name,cb]);queueMicrotask(()=>cb(snapshot(q.name)));return()=>{};};
export const getDocs=async()=>({docs:[]});
export const httpsCallable=()=>async body=>{window.__fixture.calls.push(body);if(receipts.has(body.operationId))return {data:receipts.get(body.operationId)};let result;
if(body.action==='saveSlip'){const raw=body.slip;const e=data.employees.find(x=>x.id===raw.employeeId);const p=periods(e).find(x=>x.id===raw.employmentId);const basis=basisAt(e,p,raw.periodStart,raw.periodEnd);const next={...raw,basis,amounts:calculate(basis,raw.attendance,raw.amounts),revision:raw.revision+1};data.payrollSlips=data.payrollSlips.filter(x=>x.id!==next.id).concat(next);result={slip:next};}
else if(body.action==='saveLegacySeptember'){const old=data.monthlySalaries.find(x=>x.id===body.id);const next={...old,...body.amounts,...body.attendance,legacySeptemberRevision:(old.legacySeptemberRevision||0)+1};data.monthlySalaries=data.monthlySalaries.map(x=>x.id===body.id?next:x);result={record:next};}
else if(body.action==='sendLegacySeptember'){result={state:'PENDING',mailId:'legacy-test-mail'};}
else if(body.action==='legacySeptemberMailStatus'){result={state:'PENDING'};}
else if(body.action==='confirm'){const s=data.payrollSlips.find(x=>x.id===body.id);s.status='confirmed';s.revision++;result={slip:{...s}};}
else if(body.action==='send'){result={state:'PENDING'};} else result={state:'NONE'};
receipts.set(body.operationId,result);for(const [name,cb] of listeners)cb(snapshot(name));if(body.action==='saveSlip'&&window.__fixture.failAfterSave){window.__fixture.failAfterSave=false;throw Error('模擬回應中斷，請重試');}return {data:result};};
export const addDoc=()=>{throw Error('Legacy send path must not execute');};
export const TaskService={subscribePayrollClients:cb=>{queueMicrotask(()=>cb([{id:'1',clientId:'1'}]));return()=>{};},subscribePayrollRecords:cb=>{queueMicrotask(()=>cb([]));return()=>{};},subscribeEmployees:cb=>{queueMicrotask(()=>cb(data.employees));return()=>{};},subscribeMonthlySalariesForClient:(id,cb)=>{queueMicrotask(()=>cb(data.monthlySalaries));return()=>{};},fetchMonthlySalaries:async()=>data.monthlySalaries,updateEmployee:async(employee,expected)=>{window.__fixture.employeeSaved={employee,expected};},addEmployee:async employee=>{window.__fixture.employeeSaved={employee,expected:null};}};
data.employees.push({...base,id:'e3',name:'復職待測',employmentType:'full_time',endDate:'2026-10-10',employmentHistory:[base.employmentHistory[0]],compensationHistory:[base.compensationHistory[0]]});
export {data};
`;
const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import {PayrollLedger} from './PayrollLedger';import {PayrollView} from './PayrollView';import {data} from 'fixture';createRoot(document.getElementById('root')).render(location.search.includes('employees')?<PayrollView clients={[{id:1,name:'本機測試客戶'}]}/>:<PayrollLedger client={{id:1,name:'本機測試客戶'}} employees={data.employees} legacy={data.monthlySalaries} initialMode="monthly" onEmployees={()=>{}} onBack={()=>{}}/>);`;
(async()=>{await build({stdin:{contents:entry,resolveDir:repo,loader:'tsx'},bundle:true,format:'iife',outfile:path.join(out,'app.js'),plugins:[{name:'mockFirebase',setup(b){b.onResolve({filter:/^(fixture|firebase\/firestore|firebase\/functions)$/},()=>({path:'mock',namespace:'fixture'}));b.onResolve({filter:/^\.\/(firebase|taskService)$/},()=>({path:'mock',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:mock,loader:'ts',resolveDir:repo}));}}]});
const server=http.createServer((req,res)=>{res.setHeader('Content-Type',req.url==='/app.js'?'application/javascript':'text/html; charset=utf-8');res.end(req.url==='/app.js'?fs.readFileSync(path.join(out,'app.js')):'<!doctype html><html lang="zh-TW"><meta charset="utf-8"><script src="https://cdn.tailwindcss.com"></script><body><div id="root"></div><script src="/app.js"></script></body></html>');});await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));const baseURL='http://127.0.0.1:'+server.address().port;let browser;
try{browser=await chromium.launch({headless:true,channel:process.env.PLAYWRIGHT_CHANNEL || 'msedge'});const page=await browser.newPage({viewport:{width:1500,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept(d.type()==='prompt'?'2026-10-20':undefined));await page.goto(baseURL);await page.getByLabel('薪資月份').fill('2026-10');await page.getByLabel('計薪員工').selectOption('e1');await page.getByLabel('任職期間').selectOption('p1');await page.getByRole('button',{name:'建立草稿',exact:true}).click();await page.getByLabel('應付本薪',{exact:true}).fill('18000');await page.getByLabel('應付伙食費',{exact:true}).fill('1500');await page.getByLabel('事假時數',{exact:true}).fill('8');assert.equal(await page.getByLabel('請假扣薪',{exact:true}).inputValue(),'1200');assert.equal(await page.getByLabel('應付伙食費',{exact:true}).inputValue(),'1500');await page.getByRole('checkbox').check();await page.evaluate(()=>window.__fixture.failAfterSave=true);await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByRole('alert').last().waitFor();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByText('草稿已保存；請確認明細後再確認薪資。').last().waitFor();const calls=await page.evaluate(()=>window.__fixture.calls.filter(c=>c.action==='saveSlip'));assert.equal(calls.length,2);assert.equal(calls[0].operationId,calls[1].operationId);await page.getByRole('button',{name:'關閉',exact:true}).click();await page.getByRole('button',{name:'確認',exact:true}).click();
await page.getByLabel('任職期間').selectOption('p2');await page.getByRole('button',{name:'建立草稿',exact:true}).click();await page.getByLabel('工作時數',{exact:true}).fill('10');assert.equal(await page.getByLabel('應付本薪',{exact:true}).inputValue(),'2200');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByText('草稿已保存；請確認明細後再確認薪資。').last().waitFor();await page.getByRole('button',{name:'關閉',exact:true}).click();await page.getByRole('button',{name:'確認',exact:true}).click();assert.equal(await page.getByRole('button',{name:'薪資單',exact:true}).count(),2);await page.getByRole('button',{name:'薪資單',exact:true}).first().click();await page.frameLocator('#salary-preview').getByText('$ 18,300',{exact:true}).waitFor();await page.getByRole('button',{name:'關閉預覽'}).click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'匯出明細與核對說明'}).click();const download=await downloadPromise;const downloaded=path.join(out,'export.xlsx');await download.saveAs(downloaded);const XLSX=require(repo+'/node_modules/xlsx');const book=XLSX.readFile(downloaded);const rows=XLSX.utils.sheet_to_json(book.Sheets['新薪資逐單']);assert.equal(rows.length,2);assert.equal(rows.reduce((n,r)=>n+r['實發'],0),20500);assert.equal(XLSX.utils.sheet_to_json(book.Sheets['舊紀錄原值']).length,2);await page.getByRole('button',{name:'年度帳冊',exact:true}).click();await page.screenshot({path:path.join(out,'annual.png'),fullPage:true});await page.goto(baseURL+'/?employees');await page.getByText('本機測試客戶',{exact:true}).click();await page.getByText('復職待測',{exact:true}).click();await page.getByRole('button',{name:'+ 新增任職／員工復職',exact:true}).click();await page.getByRole('button',{name:'確認存檔',exact:true}).click();await page.waitForFunction(()=>!!window.__fixture.employeeSaved);const saved=await page.evaluate(()=>window.__fixture.employeeSaved);assert.equal(saved.employee.endDate,'');assert.equal(saved.employee.employmentHistory.length,2);assert.equal(saved.employee.employmentHistory[0].endDate,'2026-10-10');assert.equal(saved.employee.compensationHistory.length,2);assert.equal(saved.employee.compensationHistory[1].baseSalary,36000);assert.equal(saved.employee.compensationHistory[1].foodAllowance,3000);await page.goto(baseURL+'/?loadFailure');await page.getByText('薪資資料尚未完整載入，暫不顯示合計或允許開單。').waitFor();assert.equal(await page.getByRole('button',{name:'建立草稿',exact:true}).count(),0);assert.equal(await page.getByRole('button',{name:'匯出明細與核對說明'}).count(),0);assert.equal(errors.length,0,errors.join('\n'));console.log('PASS: browser same-month rehire, manual amounts, historical rates, retry identity, confirmation, separate previews, Excel preserved legacy, annual screen and employee rehire editor; no page errors.');}
finally{if(browser)await browser.close();server.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
