const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),cp=require('node:child_process');
const repo=(process.env.PAYROLL_REPO||path.resolve(__dirname,'..')).replaceAll(String.fromCharCode(92),'/');
const {build}=require(repo+'/node_modules/esbuild');
const {chromium}=require(process.env.PLAYWRIGHT_MODULE||'playwright');
const out=fs.mkdtempSync(path.join(require('node:os').tmpdir(),'aristo-payroll-layout-'));
let mock=fs.readFileSync(repo+'/tests/payroll-ui.test.cjs','utf8').split('const mock=`')[1].split('\n`;')[0].replaceAll('${repo}',repo);
mock=mock.replace('data:()=>row','data:()=>row.amounts?{...row,amounts:Object.fromEntries(Object.entries(row.amounts).reverse()),attendance:Object.fromEntries(Object.entries(row.attendance).reverse()),basis:Object.fromEntries(Object.entries(row.basis).reverse())}:row');
mock+=`\nif(location.search.includes('baselineFixture')){data.employees=[{...base,id:'e4',name:'排版測試員工',employmentType:'full_time',startDate:'2026-10-01',endDate:'',employmentHistory:[{id:'p4',type:'full_time',startDate:'2026-10-01',endDate:null}],compensationHistory:[base.compensationHistory[0]]}];data.monthlySalaries=[{...zero,id:'layout-old',clientId:'1',employeeId:'e4',month:'2026-10',baseSalary:36000,foodAllowance:3000}];}\n`;
mock+=`\nif(location.search.includes('hiddenFixture')){data.employees.push({...base,id:'hidden-employee',name:'暫藏員工',temporaryPayrollHidden:true});data.monthlySalaries.push({...zero,id:'hidden-old',clientId:'1',employeeId:'e2',month:'2026-10',temporaryPayrollHidden:true});}\n`;
mock+=`\nif(location.search.includes('septemberFixture')){data.employees=[{...base,id:'e2',name:'舊資料測試員工',employmentType:'full_time',startDate:'2025-01-01',employmentHistory:[{id:'p2',type:'full_time',startDate:'2025-01-01',endDate:null}],compensationHistory:[{...base.compensationHistory[0],id:'c2',effectiveDate:'2025-01-01'}]},{...base,id:'e4',name:'9月復職測試',employmentType:'part_time',endDate:'',employmentHistory:[{id:'past',type:'part_time',startDate:'2025-01-01',endDate:'2025-02-28'},{id:'return',type:'part_time',startDate:'2026-09-12',endDate:null}],compensationHistory:[{...base.compensationHistory[1],id:'return-pay',effectiveDate:'2026-09-12'}]}];data.monthlySalaries=[{...zero,id:'sep-old',clientId:'1',employeeId:'e2',month:'2026-09',baseSalary:30000,foodAllowance:3000,holidayOt:8,taxFreeOt:1100},{...zero,id:'sep-hidden',clientId:'1',employeeId:'e2',month:'2026-09',temporaryPayrollHidden:true}];}\n`;
const baseline=cp.execFileSync('git',['-c','safe.directory='+repo,'show','6f25821:PayrollView.tsx'],{cwd:repo,encoding:'utf8'});
fs.writeFileSync(path.join(out,'baseline.tsx'),baseline);
async function bundle(old){const entry=`import React from 'react';import {createRoot} from 'react-dom/client';import {PayrollView} from 'view';createRoot(document.getElementById('root')).render(<PayrollView clients={[{id:1,name:'本機測試客戶'}]}/>);`;
await build({stdin:{contents:entry,resolveDir:repo,loader:'tsx'},bundle:true,format:'iife',outfile:path.join(out,old?'baseline.js':'app.js'),plugins:[{name:'fixture',setup(b){b.onResolve({filter:/^view$/},()=>({path:old?'baseline':'current',namespace:'view'}));b.onLoad({filter:/.*/,namespace:'view'},()=>({contents:old?baseline:fs.readFileSync(repo+'/PayrollView.tsx','utf8'),loader:'tsx',resolveDir:repo}));b.onResolve({filter:/^(firebase\/firestore|firebase\/functions)$/},()=>({path:'mock',namespace:'fixture'}));b.onResolve({filter:/^\.\/(firebase|taskService)$/},()=>({path:'mock',namespace:'fixture'}));b.onLoad({filter:/.*/,namespace:'fixture'},()=>({contents:mock,loader:'ts',resolveDir:repo}));}}]});}
(async()=>{await bundle(true);await bundle(false);const server=http.createServer((req,res)=>{const filename=req.url==='/baseline.js'?'baseline.js':req.url==='/app.js'?'app.js':null;res.setHeader('Content-Type',filename?'application/javascript':'text/html; charset=utf-8');res.end(filename?fs.readFileSync(path.join(out,filename)):`<!doctype html><html lang="zh-TW"><meta charset="utf-8"><script src="https://cdn.tailwindcss.com"></script><style>html,body,#root{height:100%;margin:0}</style><body><div id="root"></div><script src="/${req.url.includes('old')?'baseline':'app'}.js"></script></body></html>`);});await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;let browser;
try{browser=await chromium.launch({headless:true,channel:'msedge'});const page=await browser.newPage({viewport:{width:1500,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept(d.type()==='prompt'?'2026-10-20':undefined));
async function open(query){await page.goto(url+query);await page.getByText('本機測試客戶',{exact:true}).click();await page.getByRole('button',{name:'每月薪資明細',exact:true}).click();await page.locator('select').first().selectOption('2026');await page.locator('select').nth(1).selectOption('10');await page.waitForFunction(()=>getComputedStyle([...document.querySelectorAll('button')].find(b=>b.textContent==='每月薪資明細')).paddingTop==='8px');await page.waitForTimeout(1000);}
async function geometry(){return page.locator('table').first().evaluate(table=>({header:[...table.querySelectorAll('thead th')].map(e=>({text:e.textContent,classes:e.className,x:e.getBoundingClientRect().x,y:e.getBoundingClientRect().y,w:e.getBoundingClientRect().width,h:e.getBoundingClientRect().height})),table:{x:table.getBoundingClientRect().x,y:table.getBoundingClientRect().y,w:table.getBoundingClientRect().width},tabs:[...document.querySelectorAll('button')].filter(b=>['員工名單','每月薪資明細','年度薪資帳冊'].includes(b.textContent)).map(b=>({text:b.textContent,x:b.getBoundingClientRect().x,y:b.getBoundingClientRect().y,w:b.getBoundingClientRect().width,h:b.getBoundingClientRect().height}))}));}
await open('/?old&baselineFixture');const original=await geometry();await page.getByText('應加金額 [+]',{exact:true}).click();const expandedBefore=await geometry();await page.getByText('應加金額 [-]',{exact:true}).click();await page.screenshot({path:path.join(out,'monthly-before.png')});await page.getByRole('button',{name:'年度薪資帳冊',exact:true}).click();const annualBefore=await geometry();await page.screenshot({path:path.join(out,'annual-before.png')});
await open('/?baselineFixture');const restored=await geometry();assert.deepEqual(restored,original,'Original monthly table and toolbar geometry must remain identical');await page.getByText('應加金額 [+]',{exact:true}).click();assert.deepEqual(await geometry(),expandedBefore,'Expanded original group geometry');await page.getByText('應加金額 [-]',{exact:true}).click();await page.screenshot({path:path.join(out,'monthly-after.png')});await page.getByText('排版測試員工',{exact:true}).click();await page.waitForFunction(()=>document.querySelector('fieldset')?.disabled===true);assert.equal(await page.getByRole('button',{name:'保存草稿',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'✕',exact:true}).click();await page.getByRole('button',{name:'年度薪資帳冊',exact:true}).click();assert.deepEqual(await geometry(),annualBefore,'Original yearly geometry must remain identical');await page.screenshot({path:path.join(out,'annual-after.png')});assert.equal(await page.getByText('36,000',{exact:true}).count(),4); // salary and its totals, meal separate
await page.getByRole('button',{name:'全螢幕',exact:true}).click();assert.equal(await page.getByRole('button',{name:'離開全螢幕',exact:true}).count(),1);await page.getByRole('button',{name:'離開全螢幕',exact:true}).click();for(const width of [1280,1920]){await page.setViewportSize({width,height:1000});await open('/?old&baselineFixture');const before=await geometry();await open('/?baselineFixture');assert.deepEqual(await geometry(),before,'Layout at viewport '+width);}await page.setViewportSize({width:1500,height:1000});await open('/');await page.getByText('復職測試員工',{exact:true}).first().click();await page.getByLabel('任職期間').selectOption('p1');



const salary=page.locator('label').filter({hasText:/本薪|應付薪資/}).first().locator('..').locator('input');await salary.fill('18000');const food=page.locator('label').filter({hasText:'伙食費'}).first().locator('..').locator('input');await food.fill('1500');await page.locator('label').filter({hasText:'事假 (時)'}).locator('..').locator('input').fill('8');assert.equal(await page.locator('label').filter({hasText:'請假扣款'}).locator('..').locator('input').inputValue(),'1200');assert.equal(await food.inputValue(),'1500');await page.getByRole('checkbox').check();await page.evaluate(()=>window.__fixture.failAfterSave=true);await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByRole('alert').last().waitFor();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByText('草稿已保存，請核對後確認薪資。').waitFor();const calls=await page.evaluate(()=>window.__fixture.calls.filter(c=>c.action==='saveSlip'));assert.equal(calls[0].operationId,calls[1].operationId);await page.getByLabel('薪資備註').fill('分段結薪測試');assert.equal(await page.getByRole('button',{name:'確認薪資',exact:true}).isDisabled(),true);await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByRole('button',{name:'確認薪資',exact:true}).click();await page.getByText('薪資已確認。',{exact:true}).waitFor();assert.equal(await salary.isDisabled(),true);await page.screenshot({path:path.join(out,'period-editor.png')});await page.getByRole('button',{name:'預覽薪資單'}).click();await page.frameLocator('#salary-preview').getByText('$ 18,300',{exact:true}).waitFor();assert.equal(await page.frameLocator('#salary-preview').locator('th').filter({hasText:'加項'}).count(),1);await page.getByRole('button',{name:'關閉預覽'}).click();await page.getByRole('button',{name:'✕',exact:true}).click();
await page.getByText('復職測試員工',{exact:true}).nth(1).click();assert.equal(await page.getByLabel('任職期間').inputValue(),'p2');await page.locator('label').filter({hasText:'出勤時數'}).locator('..').locator('input').fill('10');assert.equal(await salary.inputValue(),'2200');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'保存草稿',exact:true}).click();await page.getByText('草稿已保存，請核對後確認薪資。').waitFor();await page.getByRole('button',{name:'確認薪資',exact:true}).click();await page.getByText('薪資已確認。',{exact:true}).waitFor();await page.getByRole('button',{name:'✕',exact:true}).click();const downloadEvent=page.waitForEvent('download');await page.getByRole('button',{name:'匯出薪資總表',exact:true}).click();const download=await downloadEvent;const file=path.join(out,'export.xlsx');await download.saveAs(file);const XLSX=require(repo+'/node_modules/xlsx');const book=XLSX.readFile(file);assert.equal(book.SheetNames.includes('舊紀錄核對'),true);const first=XLSX.utils.sheet_to_json(book.Sheets[book.SheetNames[0]],{header:1});assert.equal(first[1][15],18300);assert.equal(first[2][15],2200);assert.equal(first[3][15],20500);assert.equal(XLSX.utils.sheet_to_json(book.Sheets['舊紀錄核對']).length,2);await page.getByRole('button',{name:'年度薪資帳冊',exact:true}).click();assert.equal(await page.getByText('18,300',{exact:true}).count()>0,false);assert.equal(await page.getByText('19,000',{exact:true}).count(),4); // yearly salary metric differs from net
await page.goto(url+'/?loadFailure');await page.getByText('本機測試客戶',{exact:true}).click();await page.getByRole('button',{name:'每月薪資明細',exact:true}).click();await page.getByText('薪資資料尚未完整載入，暫不顯示合計或允許開單。').waitFor();assert.equal(await page.getByRole('button',{name:'匯出薪資總表',exact:true}).isDisabled(),true);assert.equal(errors.length,0,errors.join('\n'));fs.writeFileSync(path.join(out,'geometry.json'),JSON.stringify({original,restored,annualBefore},null,2));console.log('PASS original monthly/yearly geometry, original styled preview/workbook, legacy readonly, same-month independent periods, manual pay, retry identity, confirmation, annual metrics and fail-closed loading.');console.log('ARTIFACTS '+out);
await page.goto(url+'/?hiddenFixture');await page.getByText('本機測試客戶',{exact:true}).click();assert.equal(await page.getByText('暫藏員工',{exact:true}).count(),0);await page.getByRole('button',{name:'每月薪資明細',exact:true}).click();await page.locator('select').first().selectOption('2026');await page.locator('select').nth(1).selectOption('10');await page.getByRole('button',{name:'核對與歷史紀錄'}).click();assert.equal(await page.getByText('hidden-old').count(),0);assert.equal(await page.getByText('old1').count(),1);
await page.goto(url+'/?septemberFixture');await page.getByText('本機測試客戶',{exact:true}).click();await page.getByRole('button',{name:'每月薪資明細',exact:true}).click();await page.locator('select').first().selectOption('2026');await page.locator('select').nth(1).selectOption('09');await page.getByText('舊資料測試員工',{exact:true}).first().click();await page.locator('label').filter({hasText:'國定加班 (時)'}).locator('..').locator('input').fill('9');await page.locator('label').filter({hasText:'免稅加班費'}).locator('..').locator('input').fill('1237');await page.getByRole('button',{name:'保存更正'}).click();await page.getByText('9 月薪資更正已保存，原值保留。').waitFor();assert.equal(await page.evaluate(()=>window.__fixture.calls.filter(x=>x.action==='saveLegacySeptember').length),1);assert.equal(await page.getByText('sep-hidden').count(),0);await page.locator('button[title="寄送薪資單"]').click();assert.equal(await page.evaluate(()=>window.__fixture.calls.filter(x=>x.action==='sendLegacySeptember').length),1);
await page.getByRole('button',{name:'取消',exact:true}).click();await page.getByText('9月復職測試',{exact:true}).first().click();assert.equal(await page.getByLabel('計薪起日').inputValue(),'2026-09-12');assert.equal(await page.getByRole('button',{name:'保存草稿',exact:true}).isEnabled(),true);
}finally{if(browser)await browser.close();server.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
