const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const vm=require('node:vm');const ts=require('typescript');
function load(file,requires={}){const code=ts.transpileModule(fs.readFileSync(file,'utf8'),{compilerOptions:{module:ts.ModuleKind.CommonJS,target:ts.ScriptTarget.ES2022}}).outputText;const exports={};vm.runInNewContext(code,{exports,require:n=>requires[n]||require(n),console,Date,Set,Map,JSON,Number,Math,Object,Array,String,Error});return exports;}
const d=load('functions/src/payrollDomain.ts');
const emp={id:'e1',clientId:'c1',name:'測試員工',email:'test@example.com',empNo:'1',startDate:'2026-01-01',endDate:'',employmentType:'full_time',defaultBaseSalary:36000,defaultFoodAllowance:3000,insuranceBracket:36000,hasLaborIns:true,hasHealthIns:true,createdAt:'2026-01-01',employmentHistory:[{id:'p1',type:'full_time',startDate:'2026-01-01',endDate:'2026-02-28'},{id:'p2',type:'part_time',startDate:'2026-04-01',endDate:null}],compensationHistory:[{id:'t1',effectiveDate:'2026-01-01',baseSalary:36000,foodAllowance:3000,insuranceBracket:36000,hasLaborIns:true,hasHealthIns:true},{id:'t2',effectiveDate:'2026-04-01',baseSalary:220,foodAllowance:0,insuranceBracket:28000,hasLaborIns:true,hasHealthIns:false}]};
const basis=d.basisAt(emp,emp.employmentHistory[0],'2026-01-01','2026-01-31');
const slip=(extra={})=>({id:'s1',schemaVersion:2,revision:0,clientId:'c1',employeeId:'e1',employmentId:'p1',month:'2026-01',periodStart:'2026-01-01',periodEnd:'2026-01-31',kind:'regular',relatedId:'',replacesId:'',status:'draft',basis,attendance:d.emptyValues(d.attendanceFields),amounts:{...d.emptyValues(d.amountFields),baseSalary:18000,foodAllowance:1500},employee:{name:emp.name,email:emp.email,empNo:'1'},company:{name:'測試客戶',phone:'',address:''},note:'',reason:'',reviewedMonth:true,createdAt:'',updatedAt:'',actor:'',...extra});
test('cross-month rehire preserves gap and supports changed employment type',()=>{d.validatePeriods(emp.employmentHistory);assert.equal(d.basisAt(emp,emp.employmentHistory[1],'2026-04-01','2026-04-30').baseSalary,220);assert.throws(()=>d.validateSlip(slip({month:'2026-03',periodStart:'2026-03-01',periodEnd:'2026-03-31'}),emp,[],[]),/任職範圍/);});
test('same month joining, leaving and rehiring uses two independent periods',()=>{const e={...emp,employmentHistory:[{id:'p1',type:'full_time',startDate:'2026-01-01',endDate:'2026-01-10'},{id:'p2',type:'part_time',startDate:'2026-01-20',endDate:null}]};const first=slip({periodEnd:'2026-01-10'});d.validateSlip(first,e,[],[]);d.validateSlip(slip({id:'s2',employmentId:'p2',periodStart:'2026-01-20'}),e,[first],[]);assert.equal(first.amounts.baseSalary,18000);});
for(const [name,ps] of [['overlapping inclusive leaving day',[{id:'a',type:'full_time',startDate:'2026-01-01',endDate:'2026-01-10'},{id:'b',type:'full_time',startDate:'2026-01-10',endDate:null}]],['two open periods',[{id:'a',type:'full_time',startDate:'2026-01-01',endDate:null},{id:'b',type:'full_time',startDate:'2026-02-01',endDate:null}]],['invalid calendar date',[{id:'a',type:'full_time',startDate:'2026-02-30',endDate:null}]]])test('rejects '+name,()=>assert.throws(()=>d.validatePeriods(ps)));
test('partial-month payable base does not reduce leave or overtime basis',()=>{const s=slip();const a=d.calculate(basis,{...s.attendance,personalLeave:8,lateHours:60,normalOt:2},s.amounts);assert.equal(a.leaveDeduction,1200);assert.equal(a.lateDeduction,150);assert.equal(a.taxFreeOt,433);assert.equal(a.baseSalary,18000);assert.equal(a.foodAllowance,1500);});
test('zero contractual and manually payable meal allowances stay zero',()=>{const s=slip();const a=d.calculate({...basis,foodAllowance:0},{...s.attendance,sickLeave:8},{...s.amounts,foodAllowance:0});assert.equal(a.foodAllowance,0);assert.equal(a.leaveDeduction,600);});
test('historical part-time rate determines holiday pay',()=>{const s=slip();assert.equal(d.calculate({...basis,employmentType:'part_time',baseSalary:200},{...s.attendance,holidayOt:2},s.amounts).taxFreeOt,800);});
test('missing initial basis and within-period rate change require explicit resolution',()=>{assert.throws(()=>d.basisAt({...emp,compensationHistory:[emp.compensationHistory[1]]},emp.employmentHistory[0],'2026-01-01','2026-01-31'));assert.throws(()=>d.basisAt({...emp,compensationHistory:[...emp.compensationHistory,{...emp.compensationHistory[0],id:'extra',effectiveDate:'2026-01-15'}]},emp.employmentHistory[0],'2026-01-01','2026-01-31'),/分開/);});
test('every legacy salary in target employee/month prevents silent double settlement',()=>assert.throws(()=>d.validateSlip(slip(),emp,[],[{employeeId:'e1',month:'2026-01'}]),/舊薪資/));
test('existing draft reserves regular salary coverage',()=>assert.throws(()=>d.validateSlip(slip({id:'s2'}),emp,[slip()],[]),/涵蓋/));
test('void salary no longer reserves regular coverage',()=>d.validateSlip(slip({id:'s2'}),emp,[slip({status:'void'})],[]));
test('correction can replace only a confirmed matching employee/month',()=>{d.validateSlip(slip({id:'s2',replacesId:'s1',reason:'更正加班'}),emp,[slip({status:'confirmed'})],[]);assert.throws(()=>d.validateSlip(slip({id:'s2',replacesId:'s1',reason:'更正'}),emp,[slip({status:'void'})],[]));});
test('duplicates, orphan and incomplete old records remain visible issues without mutations',()=>{const list=[{id:'o1',clientId:'c1',employeeId:'missing',month:'2026-01'},{id:'o2',clientId:'c1',employeeId:'missing',month:'2026-01'}];const before=JSON.stringify(list);assert.equal(d.legacyIssues(list[0],list,[]).length,3);assert.equal(JSON.stringify(list),before);});
test('HTML previews escape names and notes and use saved monetary values',()=>{const s=slip({note:'<script>alert(1)</script>'});const html=d.slipHtml(s);assert(!html.includes('<script>'));assert(html.includes('&lt;script&gt;'));assert(html.includes('19,500'));});

function setup(extra={}) {
 const docs=new Map(Object.entries({'googleUserProfiles/auth':{userId:'u1'},'users/u1':{role:'intern',isActive:true,googleUid:'auth',permissions:{payroll:true}},'clients/c1':{name:'測試客戶'},'payrollClients/config':{clientId:'c1'},'employees/e1':emp,...extra}));let writes=[];
 const ref=p=>({path:p});const snap=p=>({id:p.split('/').pop(),ref:ref(p),exists:docs.has(p),data:()=>docs.get(p)});
 const db={doc:ref,collection:p=>({where:(field,op,value)=>({collection:p,field,value})}),runTransaction:async cb=>{const staged=[];let wrote=false;const result=await cb({get:async r=>{assert(!wrote,'Firestore prohibits reads after writes');if(r.collection){const matches=[...docs.keys()].filter(p=>p.startsWith(r.collection+'/')&&p.split('/').length===2&&docs.get(p)[r.field]===r.value).map(snap);return {docs:matches,empty:matches.length===0};}return snap(r.path);},set:(r,v,options)=>{wrote=true;staged.push({path:r.path,value:options?.merge?{...docs.get(r.path),...v}:v});},create:(r,v)=>{wrote=true;assert(!docs.has(r.path),'create must not overwrite');staged.push({path:r.path,value:v});}});for(const w of staged)docs.set(w.path,w.value);writes.push(...staged);return result;}};
 class HttpsError extends Error {constructor(code,message){super(message);this.code=code;}}
 const mod=load('functions/src/payroll.ts',{'firebase-admin/firestore':{getFirestore:()=>db},'firebase-functions/v2/https':{onCall:(_,fn)=>fn,HttpsError},'./payrollDomain.js':d});let n=0;
 const call=(data,auth={uid:'auth'})=>mod.payrollCommand({auth,data:{clientId:'c1',operationId:'op'+(++n),...data}});
 return {docs,call,writes};
}
test('save is idempotent across a network retry and changes no legacy documents',async()=>{const s=setup({'monthlySalaries/old':{clientId:'c1',employeeId:'other',month:'2026-01'}});const body={action:'saveSlip',slip:slip(),expectedRevision:0,operationId:'fixed'};const r=await s.call(body);assert.equal(r.slip.revision,1);await s.call(body);assert.equal(s.docs.get('payrollSlips/s1').revision,1);assert(!s.writes.some(w=>w.path.startsWith('monthlySalaries/')));});
test('revoked source user cannot write even if profile exists',async()=>{const s=setup({'users/u1':{role:'intern',googleUid:'auth',permissions:{payroll:false}}});await assert.rejects(()=>s.call({action:'saveSlip',slip:slip(),expectedRevision:0}),/權限/);assert.equal(s.writes.length,0);});
test('unauthenticated write rejected',async()=>{const s=setup();await assert.rejects(()=>s.call({action:'saveSlip',slip:slip(),expectedRevision:0},null),/登入/);});
test('cannot overwrite another client using a colliding salary ID',async()=>{const s=setup({'payrollSlips/s1':slip({clientId:'c2',revision:1})});await assert.rejects(()=>s.call({action:'saveSlip',slip:slip(),expectedRevision:0}),/客戶/);});
test('confirmed salaries are immutable and confirmation is a saved version',async()=>{const s=setup();await s.call({action:'saveSlip',slip:slip(),expectedRevision:0});const r=await s.call({action:'confirm',id:'s1',expectedRevision:1});assert.equal(r.slip.status,'confirmed');assert(s.docs.has('payrollSlips/s1/versions/2'));await assert.rejects(()=>s.call({action:'saveSlip',slip:slip(),expectedRevision:2}),/不能直接修改/);});
test('correction confirmation atomically supersedes original; original remains until then',async()=>{const s=setup({'payrollSlips/s1':slip({status:'confirmed',revision:2})});await s.call({action:'saveSlip',slip:slip({id:'s2',replacesId:'s1',reason:'補正加班'}),expectedRevision:0});assert.equal(s.docs.get('payrollSlips/s1').status,'confirmed');await s.call({action:'confirm',id:'s2',expectedRevision:1});assert.equal(s.docs.get('payrollSlips/s1').status,'superseded');assert.equal(s.docs.get('payrollSlips/s2').status,'confirmed');});
test('cannot confirm stale basis after employee treatment changes',async()=>{const s=setup();await s.call({action:'saveSlip',slip:slip(),expectedRevision:0});s.docs.set('employees/e1',{...emp,compensationHistory:[{...emp.compensationHistory[0],baseSalary:38000},emp.compensationHistory[1]]});await assert.rejects(()=>s.call({action:'confirm',id:'s1',expectedRevision:1}),/待遇已變更/);});
test('send requires confirmation, snapshots exact revision, and blocks duplicate dispatch',async()=>{const s=setup();await s.call({action:'saveSlip',slip:slip(),expectedRevision:0});await assert.rejects(()=>s.call({action:'send',id:'s1',expectedRevision:1}),/已確認/);await s.call({action:'confirm',id:'s1',expectedRevision:1});const sent=await s.call({action:'send',id:'s1',expectedRevision:2});assert.equal(s.docs.get('mail/'+sent.mailId).salaryVersion,2);const again=await s.call({action:'send',id:'s1',expectedRevision:2});assert.equal(again.alreadyQueued,true);assert.equal([...s.docs.keys()].filter(k=>k.startsWith('mail/')).length,1);});
test('only failed delivery can be retried, creating a distinct recorded attempt',async()=>{const s=setup({'payrollSlips/s1':slip({status:'confirmed',revision:2})});const r=await s.call({action:'send',id:'s1',expectedRevision:2});s.docs.get('mail/'+r.mailId).delivery={state:'ERROR'};const retry=await s.call({action:'send',id:'s1',expectedRevision:2,retry:true});assert.notEqual(retry.mailId,r.mailId);assert.equal(s.docs.get('payrollDispatch/s1_2').attempt,2);});
test('saving open rehire clears master departure and protects referenced periods',async()=>{const source={...emp,endDate:'2026-02-28'};const s=setup({'employees/e1':source});await s.call({action:'saveEmployee',employee:source,expected:source});assert.equal(s.docs.get('employees/e1').endDate,'');const original=s.docs.get('employees/e1');s.docs.set('payrollSlips/s1',slip({revision:1}));await assert.rejects(()=>s.call({action:'saveEmployee',employee:{...original,employmentHistory:[emp.employmentHistory[1]]},expected:original}),/已有薪資引用/);});
test('employee save detects stale forms but does not depend on property ordering',async()=>{const s=setup();const reversed=Object.fromEntries(Object.entries(emp).reverse());await s.call({action:'saveEmployee',employee:emp,expected:reversed});await assert.rejects(()=>s.call({action:'saveEmployee',employee:emp,expected:{...emp,name:'stale'}}),/已變更/);});
test('void requires reason and preserves previous versions',async()=>{const s=setup();await s.call({action:'saveSlip',slip:slip(),expectedRevision:0});await assert.rejects(()=>s.call({action:'void',id:'s1',expectedRevision:1}),/原因/);await s.call({action:'void',id:'s1',expectedRevision:1,reason:'取消重開'});assert.equal(s.docs.get('payrollSlips/s1').status,'void');assert(s.docs.has('payrollSlips/s1/versions/1'));});
test('annual categories preserve the original category formula without deducting withholding twice',()=>{const a={...slip().amounts,fullAttendance:1000,performanceBonus:2000,leaveDeduction:1200,pensionSelf:500,laborIns:1000};const metrics=d.annualMetrics(a);assert.equal(metrics['薪資總額'],17800);assert.equal(metrics['獎金'],2000);assert.equal(metrics['伙食費'],1500);assert.equal(metrics['實發'],19800);});
test('supplement needs a confirmed source and reason, while regular overlap remains forbidden',()=>{const original=slip({status:'confirmed',revision:2});const extra=slip({id:'s2',kind:'supplement',relatedId:'s1',reason:'補發獎金'});d.validateSlip(extra,emp,[original],[]);assert.throws(()=>d.validateSlip({...extra,reason:''},emp,[original],[]));assert.throws(()=>d.validateSlip({...extra,relatedId:'wrong'},emp,[original],[]));});
test('legacy linked history cannot disappear when saving employee',async()=>{const s=setup({'monthlySalaries/old':{clientId:'c1',employeeId:'e1',month:'2026-01'}});await assert.rejects(()=>s.call({action:'saveEmployee',employee:{...emp,employmentHistory:[emp.employmentHistory[1]]},expected:emp}),/保留既有任職/);assert.equal(s.writes.length,0);});
test('new employee creation can be retried after acknowledgement loss without duplication',async()=>{const s=setup();const newEmp={...emp,id:'new'};const request={action:'saveEmployee',employee:newEmp,expected:null,operationId:'newEmployee'};await s.call(request);await s.call(request);assert.equal([...s.docs.keys()].filter(k=>k==='employees/new').length,1);});
test('receipt cannot be reused with a changed body',async()=>{const s=setup();await s.call({action:'saveSlip',slip:slip(),expectedRevision:0,operationId:'same'});await assert.rejects(()=>s.call({action:'saveSlip',slip:slip({note:'changed'}),expectedRevision:0,operationId:'same'}),/重試內容不一致/);});
